Table CUSTOMER_H [headercolor: #5BD1FA]{

HK_CUSTOMER_H text [primary key]
C_CUSTKEY text
ldts timestamp_ntz
rsrc text

}


Table ORDERS_H [headercolor: #5BD1FA]{

HK_ORDER_H text [primary key]
O_ORDERKEY text
ldts timestamp_ntz
rsrc text

}


Table PART_H [headercolor: #5BD1FA]{

HK_PART_H text [primary key]
P_PARTKEY text
ldts timestamp_ntz
rsrc text

}


Table SUPPLIER_H [headercolor: #5BD1FA]{

HK_SUPPLIER_H text [primary key]
S_SUPPKEY text
ldts timestamp_ntz
rsrc text

}


Table ORDERS_CUSTOMERS_L [headercolor: #EF7070]{

HK_ORDERS_CUSTOMERS_L text [primary key]
HK_ORDER_H text [ref: <> ORDERS_H.HK_ORDER_H]
HK_CUSTOMER_H text [ref: <> CUSTOMER_H.HK_CUSTOMER_H]
ldts timestamp_ntz
rsrc text

}


Table PART_SUPPLIER_L [headercolor: #EF7070]{

HK_PART_SUPPLIER_L text [primary key]
HK_PART_H text [ref: <> PART_H.HK_PART_H]
HK_SUPPLIER_H text [ref: <> SUPPLIER_H.HK_SUPPLIER_H]
ldts timestamp_ntz
rsrc text

}


Table LINEITEM_NL [headercolor: #EF7070]{

HK_LINEITEM_NL text [primary key]
HK_PART_H text [ref: <> PART_H.HK_PART_H]
HK_ORDER_H text [ref: <> ORDERS_H.HK_ORDER_H]
HK_SUPPLIER_H text [ref: <> SUPPLIER_H.HK_SUPPLIER_H]
L_LINENUMBER text
L_QUANTITY text
L_EXTENDEDPRICE text
L_DISCOUNT text
L_TAX text
L_RETURNFLAG text
L_LINESTATUS text
L_SHIPDATE text
L_COMMITDATE text
L_RECEIPTDATE text
L_SHIPINSTRUCT text
L_SHIPMODE text
L_COMMENT text
ldts timestamp_ntz
rsrc text

}


Table CUSTOMER_N_S [headercolor: #FBE870]{

HK_CUSTOMER_H text [primary key,ref: <> CUSTOMER_H.HK_CUSTOMER_H]
hd_CUSTOMER_N_S text 
ldts timestamp_ntz
rsrc text
C_ACCTBAL text
C_MKTSEGMENT text
C_COMMENT text

}


Table CUSTOMER_P_S [headercolor: #FBE870]{

HK_CUSTOMER_H text [primary key,ref: <> CUSTOMER_H.HK_CUSTOMER_H]
hd_CUSTOMER_P_S text 
ldts timestamp_ntz
rsrc text
C_NAME text
C_ADDRESS text
C_PHONE text

}


Table ORDERS_N_S [headercolor: #FBE870]{

HK_ORDER_H text [primary key,ref: <> ORDERS_H.HK_ORDER_H]
hd_ORDERS_N_S text 
ldts timestamp_ntz
rsrc text
O_CLERK text
O_COMMENT text
O_ORDERDATE text
O_ORDERPRIORITY text
O_ORDERSTATUS text
O_SHIPPRIORITY text
O_TOTALPRICE text

}


Table PART_N_S [headercolor: #FBE870]{

HK_PART_H text [primary key,ref: <> PART_H.HK_PART_H]
hd_PART_N_S text 
ldts timestamp_ntz
rsrc text
P_BRAND text
P_COMMENT text
P_CONTAINER text
P_MFGR text
P_NAME text
P_RETAILPRICE text
P_SIZE text

}


Table SUPPLIER_P_S [headercolor: #FBE870]{

HK_SUPPLIER_H text [primary key,ref: <> SUPPLIER_H.HK_SUPPLIER_H]
hd_SUPPLIER_P_S text 
ldts timestamp_ntz
rsrc text
S_ADDRESS text
S_NAME text

}


Table SUPPLIER_N_S [headercolor: #FBE870]{

HK_SUPPLIER_H text [primary key,ref: <> SUPPLIER_H.HK_SUPPLIER_H]
hd_SUPPLIER_N_S text 
ldts timestamp_ntz
rsrc text
S_ACCTBAL text

}


Table PART_SUPPLIER_N_S [headercolor: #FBE870]{

HK_PART_SUPPLIER_L text [primary key,ref: <> PART_SUPPLIER_L.HK_PART_SUPPLIER_L]
hd_PART_SUPPLIER_N_S text 
ldts timestamp_ntz
rsrc text
PS_AVAILQTY text
PS_COMMENT text
PS_SUPPLYCOST text

}



TableGroup sources {

}

TableGroup sources {

}

TableGroup sources {

}

TableGroup sources {

}

TableGroup sources {

}

TableGroup sources {

}
